import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import { Heading, Nav } from '@components/ui'
import { BackgroundBeamsWithCollision } from '@components/aceternity'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const rubik = Rubik({ subsets: ['latin'] })

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='dark'>
			<body className={`${rubik.className} antialiased dark:text-white text-black`}>
				<BackgroundBeamsWithCollision className='-z-10 fixed top-0 left-0 h-screen md:h-screen' />
				<main className='max-w-2xl mx-auto w-11/12 py-8'>
					<Heading />
					<Nav />
					{children}
				</main>
			</body>
		</html>
	)
}
